apiVersion: 1

datasources:
  - name: OpenSearch
    type: elasticsearch
    access: proxy
    url: http://opensearch:9200
    jsonData:
      database: "[calls-]YYYY.MM.DD"
      timeField: "@timestamp"
      version: "8.0.0"
      maxConcurrentShardRequests: 5
      timeInterval: "10s"
      logMessageField: "message"
      logLevelField: "level"