apiVersion: 1

datasources:
  - name: OpenSearch
    type: grafana-opensearch-datasource
    access: proxy
    url: http://opensearch:9200
    isDefault: true
    basicAuth: true
    basicAuthUser: "admin"
    secureJsonData:
      basicAuthPassword: "admin"
    jsonData:
      database: "calls-*"
      flavor: "opensearch"
      logLevelField: ""
      logMessageField: ""
      maxConcurrentShardRequests: 5
      pplEnabled: true
      timeField: "@timestamp"
      version: "2.11.1"
      versionLabel: "OpenSearch 2.11.1"
      timeInterval: "1m"
      timezone: "Europe/Rome"