version: '3.8'

services:
  rule-manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_USER=${OPENSEARCH_USER:-admin}
      - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD:-admin}
      - FLINK_URL=http://jobmanager:8081
    depends_on:
      - jobmanager
    networks:
      - fraud-network
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-u", "admin:admin", "-f", "http://opensearch:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  jobmanager:
    image: apache/flink:2.0.0
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./sql-rules:/opt/flink/sql-rules
      - ./lib/flink-sql-connector-kafka-4.0-SNAPSHOT.jar:/opt/flink/lib/flink-sql-connector-kafka-4.0-SNAPSHOT.jar
      - ./lib/flink-sql-connector-opensearch2-2.0-SNAPSHOT.jar:/opt/flink/lib/flink-sql-connector-opensearch2-2.0-SNAPSHOT.jar
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.process.size: 1600m
        jobmanager.memory.jvm.heap.size: 1024m
        python.executable: python3
    networks:
      - fraud-network

  taskmanager:
    image: apache/flink:2.0.0
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./lib/flink-sql-connector-kafka-4.0-SNAPSHOT.jar:/opt/flink/lib/flink-sql-connector-kafka-4.0-SNAPSHOT.jar
      - ./lib/flink-sql-connector-opensearch2-2.0-SNAPSHOT.jar:/opt/flink/lib/flink-sql-connector-opensearch2-2.0-SNAPSHOT.jar
    environment:
      - |
        FLINK_PROPERTIES=
        taskmanager.memory.process.size: 2048m
        taskmanager.memory.task.heap.size: 512m
        taskmanager.memory.managed.size: 512m
        taskmanager.numberOfTaskSlots: 2
        jobmanager.rpc.address: jobmanager
        python.executable: python3
    networks:
      - fraud-network

networks:
  fraud-network:
    external: true
  rules-network:
    driver: bridge
